// Generated by CoffeeScript 1.11.1
var Event, Type, frozen;

frozen = require("Property").frozen;

Type = require("Type");

Event = require("./Event");

Type.extend("defineEvents", function(events) {
  return this.initInstance(function() {
    var key, options, types;
    for (key in events) {
      types = events[key];
      options = types ? {
        types: types
      } : void 0;
      frozen.define(this, key, {
        value: Event(options)
      });
    }
  });
});
