// Generated by CoffeeScript 1.12.4
var Event, Type, frozen;

frozen = require("Property").frozen;

Type = require("Type");

Event = require("./Event");

Type.extend("defineEvents", function(events) {
  return this.initInstance(function() {
    var ctr, key, types;
    ctr = this.constructor.name;
    for (key in events) {
      types = events[key];
      frozen.define(this, key, {
        value: Event({
          id: ctr + "." + key,
          types: types
        })
      });
    }
  });
});
