// Generated by CoffeeScript 1.12.4
var Event, Listener, ListenerArray, Type, assertTypes, frozen, isDev, type;

require("LazyVar");

frozen = require("Property").frozen;

assertTypes = require("assertTypes");

isDev = require("isDev");

Type = require("Type");

ListenerArray = require("./ListenerArray");

Listener = require("./Listener");

type = Type("Event");

type.defineArgs({
  id: String.Maybe,
  types: Object.Maybe
});

type.defineFrozenValues(function(options) {
  return {
    id: options.id
  };
});

type.defineValues(function(options) {
  if (options == null) {
    options = {};
  }
  return {
    types: options.types,
    _events: options._events,
    _listeners: !options._events ? null : void 0
  };
});

type.defineMethods({
  emit: function(data) {
    if (isDev && this.types) {
      assertTypes(data, this.types);
    }
    if (this._events) {
      return this._events.emit(this.id, data);
    }
    if (this._listeners) {
      return this._listeners.notify(data);
    }
  },
  on: function(callback) {
    if (this._events) {
      return this._events.on(this.id, callback);
    } else {
      return this._on(callback);
    }
  },
  once: function(callback) {
    if (this._events) {
      return this._events.once(this.id, callback);
    } else {
      return this._on(function(data) {
        callback.call(this, data);
        return this.detach();
      });
    }
  },
  _on: function(callback) {
    var listener;
    if (!this._listeners) {
      this._listeners = ListenerArray({
        onAttach: this._onAttach.bind(this)
      });
    }
    listener = Listener(callback);
    this._listeners.attach(listener);
    return listener;
  },
  _onAttach: function(listener) {
    return Event.didAttach.emit(listener, this);
  }
});

type.defineStatics({
  Listener: Listener,
  Map: {
    lazy: function() {
      return require("./EventMap");
    }
  },
  installMixin: function() {
    return require("./EventMixin");
  },
  getListeners: function(callback) {
    var listeners, onAttach;
    listeners = [];
    onAttach = this.didAttach.on(function(listener) {
      return listeners.push(listener);
    });
    callback();
    onAttach.detach();
    return listeners;
  },
  didAttach: {
    get: function() {
      var didAttach;
      frozen.define(this, "didAttach", {
        value: didAttach = Event()
      });
      frozen.define(didAttach, "_onAttach", {
        value: emptyFunction
      });
      return didAttach;
    }
  }
});

module.exports = Event = type.build();
